name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr-title:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 15.x ]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Validate
        uses: ./